### ISSUE TITLE
Update tasklists

### ISSUE THREAD

**Issue by SarahFriedman-NOAA** [afsc-gap-products/RACE_Survey_App#11]
### Issue
Reminder to update tasklist documentation on app next year. @MargaretSiple-NOAA took thorough notes that need to be incorporated in the future.

Incorporate Ned's "files from boats" list: 

- Catch
o   RawData csvs
o   Reports by haul
-  CTD
o   .hex
o   .xml
o   .xmlcon
-  ES60
o   Raw data
- Globe
o   Logs (.glg)
o   Tracks (.mdb)
- Haul
o   .BTD, .BTH
o   .hobo
o   .marp
o   Haul reports from Wheelhouse (pdf)
o   Calculation reports from Calypso (pdf)
o   Graph image from Calypso
o   *bc2.csv
o   .marp
-  Light
o   .txt
o   .wch
o   .mk9
o   .tmp
- Marport
o   .bvdr
- Photos
o   .jpg
- Station Log (electronic)
o   .mdb
- Station Progression xlsx spreadsheet
- Nor Eastern Trawl net repair xlsx spreadsheet

And Paul's reminders of things to do:
- get the skipper's station log sheet back from Brian
- retrieve the ES60 hard drive and place it in the small black Pelican case labeled "ES60 HD AKP AI 2024"
- retrieve both the light meters, including the one on the wheelhouse rooftop?
- download the data from both light meters, following the instructions in in the lightmeter bag
- ES60 hard drive (hand carry)

**Comment by MargaretSiple-NOAA** [comment]
Thank you Sarah! I requested edit access to the [survey_app_data sheet](https://docs.google.com/spreadsheets/d/1AIQ0JEUA20D-g32uRQfRMZb0wW4SXl2n8Lwb_62uW-o/edit?gid=78571395#gid=78571395) so I can add these, but haven't gotten it yet. When I do, I'll add both these lists plus the edits I made on the boat.

**Comment by MargaretSiple-NOAA** [comment]
Do we still need this to-do list item about the photos? "CATCH computer - Add metadata to photos and make copies of Portfolio DB and Photos from leg directory (C:/Data/Photos)" -- I thought we did away with Portfolio but it might have been wishful thinking.

**Comment by SarahFriedman-NOAA** [comment]
Good catch! I've removed this from the tasklist.

**Comment by MargaretSiple-NOAA** [comment]
OK sweet -- I think I've added everything, including Ned's list of file types to the /files directory on the G Drive. I didn't remove any of the to do list items from the Data Administration section because I didn't want to remove anyone's work, but there may be some redundancy there.
